### PR TITLE
Fixes #20

### LINKED ISSUE #20: Three argument form of `felzenszwalb` errors with `Matrix{Bool}`
```
julia> felzenszwalb(rand(Bool, 10, 10), 10)
Segmented Image with:
         labels map: 10×10 Array{Int64,2}
         number of labels: 3

julia> felzenszwalb(rand(Bool, 10, 10), 10, 10)
ERROR: InexactError()
Stacktrace:
 [1] convert(::Type{Int64}, ::Float64) at ./float.jl:679
 [2] setindex!(::Dict{Int64,Int64}, ::Float64, ::Int64) at ./dict.jl:420
 [3] felzenszwalb(::Array{Bool,2}, ::Int64, ::Int64) at /home/mauro/.julia/v0.6/ImageSegmentati
on/src/felzenszwalb.jl:114                                                                    
```

### PR DESCRIPTION
**Pull request by mauro3**
This fixes #20 for me.  Although, I don't understand what this line does, so please check that \div is correct.

### CODE REVIEW

**Comment by timholy** [comment]
Thanks for contributing this!

I'd say a better fix would be to change the allocation of the result type (all the `Images.accum(T)` lines) to call something like this:
```julia
meantype(::Type{T}) where T = Images.accum(T)
meantype(::Type{T}) where T<:Integer = Float64
```
Could you throw in a test, too? The demo in #20 would be perfect.

**Comment by mauro3** [comment]
Updated (some trailing whitespace was also removed)

**Comment by timholy** [comment]
Lovely, many thanks!

**Comment by timholy** [comment]
New release submitted to METADATA.

**Pull request merged**
