### PR TITLE
[compat] MetaGraphs 0.8

### PR DESCRIPTION
**Pull request by christiangnrd**

### CODE REVIEW

**Comment by henry2004y** [comment]
Glad to see the patch bump. This was limiting my JLD2 version to v0.4.x while adding Images.jl. The original limiter was MetaGraphs.jl, but since there are multiple packages with versions < 1.x, each of them needs to be updated sequentially, which is a bit annoying.

**Comment by henry2004y** [comment]
Any plan to merge this soon?

**Comment by JonasIsensee** [comment]
Hi!
Kind bump, it'd be really neat if this could be merged and released.
The MetaGraphs 0.8 release could have likely been a patch version increase.

**Comment by christiangnrd** [comment]
@timholy I'm sorry to bother you. Would you be able to review/merge/release this when you have a few minutes? I took a quick look at the commits between MetaGraphs.jl v0.7.2 and v0.8.0 it seems like the breaking changes have to do with saving the graphs, so it's probably safe to merge this as-is.

If it makes it easier for you, I can include the bump to v1.8.3 in this PR.

**Comment by timholy** [comment]
Thanks! https://github.com/JuliaRegistries/General/pull/120129

**Pull request merged**
